FROM tiangolo/uvicorn-gunicorn:python3.10-slim

RUN apt update && apt upgrade -y && apt install -y make

ARG DB_CONNECTION
ARG MODE

ENV SQLALCHEMY_DATABASE_URI=${DB_CONNECTION}
ENV MODE=${MODE}

COPY ./requirements/base.txt .
COPY ./requirements/dev.txt .
RUN pip install -r base.txt && pip install -r dev.txt

WORKDIR /app/
EXPOSE 8080
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]